-- English localization (Default)
local L = LibStub("AceLocale-3.0"):NewLocale("MultiBars", "enUS", true)

if L then
	L.MultiBarAspect = "Aspects"
	L.MultiBarBlessing = "Blessings"
	L.MultiBarBuff = "Buff Food"
	L.MultiBarConsumable = "Consumables"
	L.MultiBarCurse = "Curses"
	L.MultiBarDemon = "Demons"
	L.MultiBarDruid = "Druid"
	L.MultiBarFeedPet = "Feed Pet"
	L.MultiBarFood = "Food and Drink"
	L.MultiBarHunterPet = "Hunter Pet"
	L.MultiBarMacro = "Macros"
	L.MultiBarMageArmor = "Mage Armor"
	L.MultiBarMageBuff = "Mage Buffs"
	L.MultiBarMagePortal = "Portals"
	L.MultiBarPriest = "Priest Buffs"
	L.MultiBarProfession = "Professions"
	L.MultiBarSeal = "Seals"
	L.MultiBarTrap = "Traps"
	
	BINDING_HEADER_MULTIBARASPECT = "MultiBars Aspect Bar";
	BINDING_NAME_MULTIBARASPECTBUTTON1 = "Aspect Button 1";
	BINDING_NAME_MULTIBARASPECTBUTTON2 = "Aspect Button 2";
	BINDING_NAME_MULTIBARASPECTBUTTON3 = "Aspect Button 3";
	BINDING_NAME_MULTIBARASPECTBUTTON4 = "Aspect Button 4";
	BINDING_NAME_MULTIBARASPECTBUTTON5 = "Aspect Button 5";
	BINDING_NAME_MULTIBARASPECTBUTTON6 = "Aspect Button 6";
	
	BINDING_HEADER_MULTIBARCURSE = "MultiBars Curse Bar";
	BINDING_NAME_MULTIBARCURSEBUTTON1 = "Curse Button 1";
	BINDING_NAME_MULTIBARCURSEBUTTON2 = "Curse Button 2";
	BINDING_NAME_MULTIBARCURSEBUTTON3 = "Curse Button 3";
	BINDING_NAME_MULTIBARCURSEBUTTON4 = "Curse Button 4";
	BINDING_NAME_MULTIBARCURSEBUTTON5 = "Curse Button 5";
	BINDING_NAME_MULTIBARCURSEBUTTON6 = "Curse Button 6";
	BINDING_NAME_MULTIBARCURSEBUTTON7 = "Curse Button 7";
	BINDING_NAME_MULTIBARCURSEBUTTON8 = "Curse Button 8";
	BINDING_NAME_MULTIBARCURSEBUTTON9 = "Curse Button 9";
	
	BINDING_HEADER_MULTIBARMACRO = "MultiBars Macro Bar";
	BINDING_NAME_MULTIBARMACROBUTTON1 = "Macro Button 1";
	BINDING_NAME_MULTIBARMACROBUTTON2 = "Macro Button 2";
	BINDING_NAME_MULTIBARMACROBUTTON3 = "Macro Button 3";
	BINDING_NAME_MULTIBARMACROBUTTON4 = "Macro Button 4";
	BINDING_NAME_MULTIBARMACROBUTTON5 = "Macro Button 5";
	BINDING_NAME_MULTIBARMACROBUTTON6 = "Macro Button 6";
	BINDING_NAME_MULTIBARMACROBUTTON7 = "Macro Button 7";
	BINDING_NAME_MULTIBARMACROBUTTON8 = "Macro Button 8";
	BINDING_NAME_MULTIBARMACROBUTTON9 = "Macro Button 9";
	BINDING_NAME_MULTIBARMACROBUTTON10 = "Macro Button 10";
	BINDING_NAME_MULTIBARMACROBUTTON11 = "Macro Button 11";
	BINDING_NAME_MULTIBARMACROBUTTON12 = "Macro Button 12";
	
	BINDING_HEADER_MULTIBARSEAL = "MultiBars Seal Bar";
	BINDING_NAME_MULTIBARSEALBUTTON1 = "Seal Button 1";
	BINDING_NAME_MULTIBARSEALBUTTON2 = "Seal Button 2";
	BINDING_NAME_MULTIBARSEALBUTTON3 = "Seal Button 3";
	BINDING_NAME_MULTIBARSEALBUTTON4 = "Seal Button 4";
	BINDING_NAME_MULTIBARSEALBUTTON5 = "Seal Button 5";
	BINDING_NAME_MULTIBARSEALBUTTON6 = "Seal Button 6";
	
	BINDING_HEADER_MULTIBARTRAP = "MultiBars Trap Bar";
	BINDING_NAME_MULTIBARTRAPBUTTON1 = "Trap Button 1";
	BINDING_NAME_MULTIBARTRAPBUTTON2 = "Trap Button 2";
	BINDING_NAME_MULTIBARTRAPBUTTON3 = "Trap Button 3";
	BINDING_NAME_MULTIBARTRAPBUTTON4 = "Trap Button 4";
end
